name: "Ronas IT: Run Laravel Test"
description: "This action runs laravel tests using docker-compose"
inputs:
  docker-compose-file-path:
    description: "Where docker-compose.yaml is located"
    required: true
    default: .${{ github.action_path }}/docker-compose.testing.yaml
runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout repository
      uses: actions/checkout@v3
    - id: copy-env-testing-to-env
      name: Copy .env.testing to .env
      run: |
        cp .env.testing .env
      shell: bash
    - id: run-docker-compose-up
      name: Run docker-compose up
      run: |
        docker-compose -f ${{ inputs.docker-compose-file-path }} up -d
      shell: bash
    - id: prepare-containers
      name: Prepare containers for running tests
      run: |
        docker-compose -f ${{ inputs.docker-compose-file-path }} exec -T nginx composer install
        docker-compose -f ${{ inputs.docker-compose-file-path }} exec -T nginx php artisan jwt:secret --env=testing
        docker-compose -f ${{ inputs.docker-compose-file-path }} exec -T nginx php artisan key:generate --env=testing
      shell: bash
    - id: run-tests
      name: Run tests
      run: |
        docker-compose -f ${{ inputs.docker-compose-file-path }} exec -T nginx php vendor/bin/phpunit --stop-on-failure ./tests/
      shell: bash
    - name: Show Logs
      if: ${{ failure() }}
      run: |
        docker-compose -f ${{ inputs.docker-compose-file-path }} exec -T nginx cat storage/logs/*.log || true
      shell: bash
