name: 'Build Laravel App'
description: 'Ronas IT -> Build Laravel App'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare .env
      run: |
        cp .env.testing .env
      shell: bash
    - name: Docker-Compose Up
      run: |
        docker-compose up -d
      shell: bash
    - name: Prepare Containers
      run: |
        docker-compose exec -T nginx composer install
        docker-compose exec -T nginx php artisan jwt:secret --env=testing
        docker-compose exec -T nginx php artisan key:generate --env=testing
      shell: bash
    - name: Run Tests
      run: |
        docker-compose exec -T nginx php vendor/bin/phpunit --stop-on-failure ./tests/
      shell: bash
    - name: Logs
      run: |
        docker-compose exec -T nginx cat storage/logs/*.log || true
      shell: bash