version: '3'

services:

  nginx:
      image: ronasit/php-nginx-dev:7.4
      working_dir: /app
      volumes:
          - ../:/app
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php

  pgsql_test:
    image: ronasit/postgres:11.9
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: forge
      POSTGRES_DB: forge
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ..:/app
    command: ["-c", "fsync=off"]